table d_icones_visuais
	lineageTag: 1fb1251d-21e7-4d9f-a61d-d8bac6feec91

	column Icone
		dataType: string
		lineageTag: 9c3cb8fb-f68c-4ddb-babd-561b647a90be
		summarizeBy: none
		sourceColumn: Icone

		annotation SummarizationSetBy = Automatic

	column 'Ordem Icone'
		dataType: int64
		formatString: 0
		lineageTag: 4cae70f6-c7d0-4271-a219-81cc358a3f6b
		summarizeBy: sum
		sourceColumn: Ordem Icone

		annotation SummarizationSetBy = Automatic

	column 'Icone URL'
		dataType: string
		lineageTag: 828823b1-6f0b-4807-a6a8-d0019cf1a3d7
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Icone URL

		annotation SummarizationSetBy = Automatic

	partition d_icones_visuais = m
		mode: import
		queryGroup: Dimensão
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("5VRNU4MwEP0vzHCyxHwUBG9AYTxUx7OdHpgSIUpJB1Loz3dDaG391ouHzpBls29fssm+yWJh3ctWKNFJa2IRGHmmsmuxzgp+2XbFxW5dTWwWg2tTDJO6tdnMprRUamOz0KYpfH3fo54h2UBSSjHG8BsYFEi9yFVpSHRqQiUXRalOY4+iqkykljU3sU7wPpI7E4ZF9cJYE7BhsQRKa/hK/WUbm7LYT7xkBJpxGzNNzdr60K1q5DM/cDAOQ981HAM5laj5KtuYlEZu6/wd/CRF/Rl+XDlyD+faZBClODfIGgBMPDBT5DswwGOIGjsnAdK34h/Xfsq/Jd6Q7ZeQ3w3M11RwioOnG8cSazlZWHe8yEZp0DOTRnoVp7Pod9JIUua6s/+Rhm+UYeycMHAC5FXeoIvBfqcM4g3ScH6sjS3UCKpgZ6aMJIRHI/lCGeP1npAiHMZRbEiHe9fdIhQFgX/jZURPxmrx3ndoSejHkD7Pw5tG7duzfAE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Icone = _t, #"Ordem Icone" = _t, #"Icone URL" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Icone", type text}, {"Ordem Icone", Int64.Type}, {"Icone URL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

