table fazendas_centroides_go_sp
	lineageTag: fd5f0b10-894c-48be-9b50-f8f7a953f60e

	column id_fazenda
		dataType: string
		lineageTag: ec97e427-7f37-45b7-a94c-b9fe151e5119
		summarizeBy: none
		sourceColumn: id_fazenda

		annotation SummarizationSetBy = Automatic

	column fazenda
		dataType: string
		lineageTag: eea8c6e5-fbc5-4ce9-a740-54592ffc6f6f
		summarizeBy: none
		sourceColumn: fazenda

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: 9ed46401-190e-40c7-8d80-b43655e18af5
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column uf
		dataType: string
		lineageTag: 4e78a812-62a9-4be4-8cff-0b84ad6a7891
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column estado
		dataType: string
		lineageTag: 2cb27041-e467-4fb3-9978-e27c2cfbe12f
		summarizeBy: none
		sourceColumn: estado

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 1ad81b63-3c0d-4666-8228-ea2d9394cf2c
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: aa6d8d6f-7d99-4fd5-a81b-b0d63a498ac7
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_talhoes
		dataType: int64
		formatString: 0
		lineageTag: 48cbc42f-907f-461e-8141-3ae00ca9cb73
		summarizeBy: none
		sourceColumn: qtd_talhoes

		annotation SummarizationSetBy = Automatic

	column area_total_ha
		dataType: double
		lineageTag: d5038ca7-69cc-47cd-a0ee-415cd37e8894
		summarizeBy: none
		sourceColumn: area_total_ha

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_predominante
		dataType: string
		lineageTag: 026d5218-8f8f-46a2-be4e-877eeecfbb42
		summarizeBy: none
		sourceColumn: status_predominante

		annotation SummarizationSetBy = Automatic

	column culturas
		dataType: string
		lineageTag: 20868700-f485-41cb-943b-900a65c60d3a
		summarizeBy: none
		sourceColumn: culturas

		annotation SummarizationSetBy = Automatic

	column label_mapa
		dataType: string
		lineageTag: 94848e3f-479f-46aa-91c8-81b5d158e359
		summarizeBy: none
		sourceColumn: label_mapa

		annotation SummarizationSetBy = Automatic

	partition fazendas_centroides_go_sp = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\Downloads HD\fazendas_centroides_go_sp.csv"),[Delimiter=";", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id_fazenda", type text}, {"fazenda", type text}, {"cidade", type text}, {"uf", type text}, {"estado", type text}, {"latitude", type number}, {"longitude", type number}, {"qtd_talhoes", Int64.Type}, {"area_total_ha", type number}, {"status_predominante", type text}, {"culturas", type text}, {"label_mapa", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

