table Medidas
	lineageTag: 3b4bff63-a98e-4568-9ff0-a012b4a069cb

	measure 'Total Fazendas Cadastradas' =
			
			DISTINCTCOUNT(dim_fazenda[id_fazenda])
		formatString: 0
		displayFolder: 00.Geral\00.Cadastros
		lineageTag: 0369f81e-138c-4830-a103-15102756eb61

	measure 'Total Talhoes Cadastrados' =
			
			DISTINCTCOUNT(dim_talhao[id_talhao])
		formatString: 0
		displayFolder: 00.Geral\00.Cadastros
		lineageTag: 8e9795bf-70be-4e39-8154-704739350830

	measure 'Area Total Cadastrada HA' =
			
			SUM(dim_talhao[area_ha])
		displayFolder: 00.Geral\00.Cadastros
		lineageTag: 94432a28-eaff-4cdf-9af3-6e79cadd758f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fazendas Monitoradas' =
			
			DISTINCTCOUNT(fato_saude_talhao[id_fazenda])
		formatString: 0
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 1dde24ae-cbd9-42a0-9ef9-22ee49330875

	measure 'Culturas Monitoradas' =
			
			DISTINCTCOUNT(fato_saude_talhao[id_cultura])
		formatString: 0
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: cecd8b89-bcdd-4b30-ad56-997a8aa08f0f

	measure 'Score Saude Medio' =
			
			AVERAGE(fato_saude_talhao[score_saude])
		formatString: 0.00
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: ef641235-b090-4dcd-bcf6-10b886bc065a

	measure 'Indice Vigor Medio' =
			
			AVERAGE(fato_saude_talhao[indice_vigor])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: e4d19a44-4f18-4e70-bb56-37c9431ffa7f

	measure 'Uniformidade Media' =
			
			AVERAGE(fato_saude_talhao[uniformidade_percentual])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 1a40747d-4c03-4d94-8eff-7a3351e74aaa

	measure 'Produtividade Estimada Media' =
			
			AVERAGE(fato_saude_talhao[produtividade_estimada])
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 6855bd6f-6743-484e-b675-c7ae031c1fc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Produtividade Historica Media' =
			
			AVERAGE(fato_saude_talhao[produtividade_historica])
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: f38d8567-412e-48f4-b741-ef3c375e94c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Desvio Produtividade %' =
			
			AVERAGE(fato_saude_talhao[desvio_produtividade_percentual])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 41d2c4d7-0e20-4273-bddb-c129935dbff5

	measure 'Chuva Acumulada MM' =
			
			SUM(fato_clima_solo[chuva_acumulada_mm])
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 8c474369-da41-4862-a84c-594ea47e8160

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Chuva Media MM' =
			
			AVERAGE(fato_clima_solo[chuva_acumulada_mm])
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: ba3e1647-997f-4bc0-b96d-30be7be8781c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dias Sem Chuva Medio' =
			
			AVERAGE(fato_clima_solo[dias_sem_chuva])
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 3339fbb2-1cb8-4b4d-a9d9-5accfc240c31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Temperatura Media C' =
			
			AVERAGE(fato_clima_solo[temperatura_media_c])
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 7d5fd4b2-f280-450f-83ac-d8a37e293448

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Umidade Solo Media %' =
			
			AVERAGE(fato_clima_solo[umidade_solo_percentual])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 164567a0-91ca-422e-a3b1-84b7d61f0c20

	measure 'Deficit Hidrico Medio MM' =
			
			AVERAGE(fato_clima_solo[deficit_hidrico_mm])
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 9ba70385-a452-4e61-aea9-23e92738d342

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Score Saúde Atual' =
			
			VAR DataAtual =
			    MAX(dim_calendario[data])
			RETURN
			CALCULATE(
			    [Score Saude Medio],
			    dim_calendario[data] = DataAtual
			)
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: 4c5a50c2-38cb-42e8-9024-fddba8311a45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Score Saude Medio - MoM' =
			
			IF (
			    NOT ISFILTERED ( dim_calendario ),
			    BLANK(),
			    CALCULATE(
			        [Score Saude Medio],
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			)
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: 979154d0-8c13-4793-ac2b-ae8c4fd12bb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Variação Score Saude Medio - MoM' =
			
			DIVIDE(
			    [Score Saude Medio] - [Score Saude Medio - MoM],
			    [Score Saude Medio - MoM]
			    )
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: c4306d2c-6367-481b-a209-78bafa88ea54

		formatStringDefinition =
				VAR _Valor = [% Variação Score Saude Medio - MoM]
				
				var _ValorFormatado = FORMAT(_Valor,"+ 0.00%; - 0.00%; 0.00%")
				
				
				RETURN
				"""" & _ValorFormatado & """"

	measure 'Tendência Saúde' =
			
			VAR Variacao = [% Variação Score Saude Medio - MoM]
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(Variacao), "Sem histórico",
			    Variacao > 2, "Melhorando",
			    Variacao < -2, "Piorando",
			    "Estável"
			)
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: f5a8d80e-bb46-4b64-9ab1-8540cc579780

	measure 'Talhoes Monitorados' =
			
			DISTINCTCOUNT(fato_saude_talhao[id_talhao])
		formatString: 0
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 63c216a7-e181-45a4-86ae-bff8bf43049b

	measure '% Rep Status por Talhao' = ```
			
			DIVIDE( [Talhoes Monitorados], 
			        CALCULATE([Talhoes Monitorados],
			        ALL(dim_status_talhao))
			        )
			```
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: eb867a4c-a379-4cef-8a99-3da5d6a18645

		formatStringDefinition = """(""0.0%"")"""

	measure 'Indice Vigor Medio - MoM' =
			
			IF (
			    NOT ISFILTERED ( dim_calendario ),
			    BLANK(),
			    CALCULATE(
			        [Indice Vigor Medio],
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: 594663dd-9a9e-498f-879f-05494fe37e65

	measure '% Variação Indice Vigor Medio - MoM' =
			
			DIVIDE(
			    [Indice Vigor Medio] - [Indice Vigor Medio - MoM],
			    [Indice Vigor Medio - MoM]
			    )
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: 692cb38f-4344-4a51-b372-97774e9f5579

		formatStringDefinition =
				VAR _Valor = [% Variação Indice Vigor Medio - MoM]
				
				var _ValorFormatado = FORMAT(_Valor,"+ 0.00%; - 0.00%; 0.00%")
				
				
				RETURN
				"""" & _ValorFormatado & """"

	measure 'Uniformidade Media - MoM' =
			
			IF (
			    NOT ISFILTERED ( dim_calendario ),
			    BLANK(),
			    CALCULATE(
			        [Uniformidade Media],
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: 57d4dc68-e0d0-4836-93b4-dc7acacb7c25

	measure '% Variação Uniformidade Media - MoM' =
			
			DIVIDE(
			    [Uniformidade Media] - [Uniformidade Media - MoM],
			    [Uniformidade Media - MoM]
			    )
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: d09e58ee-6136-46f7-8565-5221b787beda

		formatStringDefinition =
				VAR _Valor = [% Variação Uniformidade Media - MoM]
				
				var _ValorFormatado = FORMAT(_Valor,"+ 0.00%; - 0.00%; 0.00%")
				
				
				RETURN
				"""" & _ValorFormatado & """"

	measure 'Talhoes Criticos' =
			
			CALCULATE(
			    [Talhoes Monitorados],
			    dim_status_talhao[ordem_status] = 3
			)
		formatString: 0
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 0c88cf6b-0e20-4163-a0c2-2c4d5b2d3927

	measure 'Talhoes Criticos - MoM' =
			
			IF (
			    NOT ISFILTERED ( dim_calendario ),
			    0,
			    CALCULATE(
			        [Talhoes Criticos],
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			)
		formatString: 0
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: f9acad22-42c8-48ad-8209-034f7b008fdf

	measure '% Variação Talhoes Criticos - MoM' =
			
			DIVIDE(
			    [Talhoes Criticos] - [Talhoes Criticos - MoM],
			    [Talhoes Criticos - MoM]
			    )
		displayFolder: 00.Geral\03.Mom e YoY
		lineageTag: 493aca50-9269-4c89-b70a-ce696ca33008

		formatStringDefinition =
				VAR _Valor = [% Variação Talhoes Criticos - MoM]
				
				var _ValorFormatado = FORMAT(_Valor,"- 0.00%; +0.00%; 0.00%")
				
				
				RETURN
				"""" & _ValorFormatado & """"

	measure 'Risco Climático Atual' =
			
			VAR _DataAtual =
			    MAX(dim_calendario[data])
			RETURN
			CALCULATE(
			    SELECTEDVALUE(fato_clima_solo[risco_climatico]),
			    dim_calendario[data] = _DataAtual
			)
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: ce2fabbc-3594-4e7c-b8d6-d822a4e34f2a
		dataCategory: Uncategorized

	measure 'Status Talhão Atual' =
			
			VAR _DataAtual =
			    MAX(dim_calendario[data])
			VAR _StatusId =
			    CALCULATE(
			        SELECTEDVALUE(fato_saude_talhao[id_status]),
			        dim_calendario[data] = _DataAtual
			    )
			RETURN
			LOOKUPVALUE(
			    dim_status_talhao[status_talhao],
			    dim_status_talhao[id_status], _StatusId
			)
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: efbb7045-e0d5-40f4-9f39-f2ca6e80c9ca

	measure 'Recomendação Atual' =
			
			VAR _DataAtual =
			    MAX(dim_calendario[data])
			VAR _StatusId =
			    CALCULATE(
			        SELECTEDVALUE(fato_notificacoes[recomendacao]),
			        dim_calendario[data] = _DataAtual
			    )
			RETURN
			COALESCE(
			    CALCULATE(
			    MAX(fato_notificacoes[recomendacao]),
			    dim_calendario[data] = _DataAtual
			    ),
			    "Sem recomendação")
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 40919148-f73f-4581-82e1-301609cb8b9d

	measure 'SVG Risco Climatico' =
			
			VAR _DataAtual =
			    MAX(dim_calendario[data])
			
			VAR _Risco =
			    CALCULATE(
			        SELECTEDVALUE(fato_clima_solo[risco_climatico]),
			        dim_calendario[data] = _DataAtual
			    )
			
			VAR _Cor =
			    SWITCH(
			        TRUE(),
			        _Risco = "Baixo", "#F59E0B",
			        _Risco = "Médio", "#3C71E3",
			        _Risco = "Alto", "#E53935",
			        "#9CA3AF"
			    )
			
			VAR _CorUrl =
			    SUBSTITUTE(_Cor, "#", "%23")
			
			VAR _Icone =
			    SWITCH(
			        TRUE(),
			
			        -- BAIXO = Sol
			        _Risco = "Baixo",
			            "<circle cx='25' cy='22' r='7' fill='none' stroke='" & _CorUrl & "' stroke-width='3'/>" &
			            "<path d='M25 4 V9 M25 35 V40 M7 22 H12 M38 22 H43 M12 9 L16 13 M38 9 L34 13 M12 35 L16 31 M38 35 L34 31' stroke='" & _CorUrl & "' stroke-width='3' stroke-linecap='round'/>",
			
			        -- MÉDIO = Nuvem com chuva
			        _Risco = "Médio",
			            "<path d='M15 26 C12 26 9 23 9 19 C9 15 12 12 16 12 C18 7 23 5 28 7 C32 8 35 12 35 16 C39 16 42 19 42 23 C42 27 39 30 35 30 H16' fill='none' stroke='" & _CorUrl & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>" &
			            "<path d='M18 36 L16 41 M27 36 L25 41 M36 36 L34 41' stroke='" & _CorUrl & "' stroke-width='3' stroke-linecap='round'/>",
			
			        -- ALTO = Nuvem com chuva e raio
			        _Risco = "Alto",
			            "<path d='M15 25 C12 25 9 22 9 18 C9 14 12 11 16 11 C18 6 23 4 28 6 C32 7 35 11 35 15 C39 15 42 18 42 22 C42 26 39 29 35 29 H16' fill='none' stroke='" & _CorUrl & "' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>" &
			            "<path d='M17 35 L15 40 M36 35 L34 40' stroke='" & _CorUrl & "' stroke-width='3' stroke-linecap='round'/>" &
			            "<path d='M26 32 L21 42 H27 L24 49 L34 36 H28 L31 32 Z' fill='" & _CorUrl & "'/>",
			
			        -- Sem risco
			        "<circle cx='25' cy='25' r='16' fill='none' stroke='" & _CorUrl & "' stroke-width='3'/>"
			    )
			
			VAR _Texto =
			    COALESCE(_Risco, "Sem risco")
			
			VAR _TextoSvg =
			    SUBSTITUTE(_Texto, "&", "&amp;")
			
			VAR _Svg =
			    "data:image/svg+xml;utf8," &
			    "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='52' viewBox='0 0 150 52'>" &
			        "<g transform='translate(0,1)'>" &
			            _Icone &
			        "</g>" &
			        "<text x='55' y='31' font-family='Segoe UI' font-size='16' font-weight='600' fill='%23182712'>" &
			            _TextoSvg &
			        "</text>" &
			    "</svg>"
			
			RETURN
			    _Svg
		displayFolder: 00.Geral\02.Clima e Solo
		lineageTag: 0ac29707-dee6-4622-b770-56be0f978eac
		dataCategory: ImageUrl

	measure 'SVG Score Saude' =
			
			VAR _ScoreOriginal = [Score Saude Medio]
			VAR _Score =
			    MIN(100, MAX(0, _ScoreOriginal))
			
			VAR _CorHex =
			    SWITCH(
			        TRUE(),
			        _Score <= 49, "#D64550",
			        _Score <= 79, "#F4C169",
			        "#699056"
			    )
			
			VAR _CorSvg =
			    SUBSTITUTE(_CorHex, "#", "%23")
			
			VAR _TextoScore =
			    FORMAT(_Score, "0.0") & "/100"
			
			VAR _BarraTotal = 120
			VAR _BarraPreenchida =
			    ROUND((_Score / 100) * _BarraTotal, 0)
			
			VAR _Svg =
			    "data:image/svg+xml;utf8," &
			    "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='52' viewBox='0 0 140 52'>" &
			        "<text x='0' y='24' font-family='Segoe UI' font-size='16' font-weight='600' fill='%23222222'>" &
			            _TextoScore &
			        "</text>" &
			        "<rect x='0' y='34' rx='4' ry='4' width='" & _BarraTotal & "' height='8' fill='%23E5E7EB'/>" &
			        "<rect x='0' y='34' rx='4' ry='4' width='" & _BarraPreenchida & "' height='8' fill='" & _CorSvg & "'/>" &
			    "</svg>"
			
			RETURN
			    _Svg
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 9ec3365b-38d1-4c5c-b0e1-c69486a30653
		dataCategory: ImageUrl

	measure 'Icone % Variação Score Medio MoM' = ```
			
			VAR _Valor = [% Variação Score Saude Medio - MoM]
			VAR _PosicaoIcones = 
			SWITCH(
			    TRUE(),
			    _Valor > 0, "Positivo",
			    _Valor < 0, "Negativo",
			    _Valor = 0, "Neutro"
			)
			VAR _Icone = 
			    CALCULATE(SELECTEDVALUE(d_Icones_Visuais[Icone URL]),d_Icones_Visuais[Icone] = _PosicaoIcones)
			
			RETURN
			_Icone
			```
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 080716e6-bcd2-42c4-8298-666a1b9b8f93

	measure 'Cor % Variação Score Medio MoM' =
			
			VAR _Valor = [% Variação Score Saude Medio - MoM]
			RETURN
			
			SWITCH(
			    TRUE(),
			    _Valor > 0, "#00AA85",
			    _Valor < 0, "#ED3559",
			    _Valor = 0, "#777A8D"
			)
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 38bdef71-1fac-4abf-9049-cff2b9b8b953

	measure 'Vs Periodo Anterior' =
			
			VAR _TemMes =
			    HASONEVALUE(dim_calendario[nome_mes])
			
			VAR _TemAno =
			    HASONEVALUE(dim_calendario[ano])
			
			VAR _DataAnterior =
			    CALCULATE(
			        MAX(dim_calendario[data]),
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			
			VAR _MesAnterior =
			    CALCULATE(
			        SELECTEDVALUE(dim_calendario[nome_mes]),
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			
			VAR _AnoAnteriorMes =
			    CALCULATE(
			        SELECTEDVALUE(dim_calendario[ano]),
			        DATEADD(dim_calendario[data], -1, MONTH)
			    )
			
			VAR _AnoAnterior =
			    SELECTEDVALUE(dim_calendario[ano]) - 1
			
			RETURN
			SWITCH(
			    TRUE(),
			    _TemMes && _TemAno,
			        "vs " & _MesAnterior & "/" & _AnoAnteriorMes & ":",
			
			    _TemAno,
			        "vs " & _AnoAnterior & ":",
			
			    " "
			)
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 2d684fc7-3002-4ee3-80af-5ee623552584

	measure 'Score Saúde Médio Texto' =
			
			FORMAT([Score Saude Medio], "0.0") & "/100"
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 6839f9a4-05a1-4d2d-84ae-1b666100dbf4

	measure 'Icone % Indice Vigor Medio MoM' = ```
			
			VAR _Valor = [% Variação Indice Vigor Medio - MoM]
			VAR _PosicaoIcones = 
			SWITCH(
			    TRUE(),
			    _Valor > 0, "Positivo",
			    _Valor < 0, "Negativo",
			    _Valor = 0, "Neutro"
			)
			VAR _Icone = 
			    CALCULATE(SELECTEDVALUE(d_Icones_Visuais[Icone URL]),d_Icones_Visuais[Icone] = _PosicaoIcones)
			
			RETURN
			_Icone
			```
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 35730d94-e10b-4477-a047-19177a0e5c39

	measure 'Cor % Variação Indice Vigor Medio MoM' =
			
			VAR _Valor = [% Variação Indice Vigor Medio - MoM]
			RETURN
			
			SWITCH(
			    TRUE(),
			    _Valor > 0, "#00AA85",
			    _Valor < 0, "#ED3559",
			    _Valor = 0, "#777A8D"
			)
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 7e1a9485-eed0-4dff-b582-2c47461ec481

	measure 'Icone % Variação Uniformidade MoM' = ```
			
			VAR _Valor = [% Variação Uniformidade Media - MoM]
			VAR _PosicaoIcones = 
			SWITCH(
			    TRUE(),
			    _Valor > 0, "Positivo",
			    _Valor < 0, "Negativo",
			    _Valor = 0, "Neutro"
			)
			VAR _Icone = 
			    CALCULATE(SELECTEDVALUE(d_Icones_Visuais[Icone URL]),d_Icones_Visuais[Icone] = _PosicaoIcones)
			
			RETURN
			_Icone
			```
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 2ea53fdc-b502-427d-a7dc-be0ecd9979f2

	measure 'Cor % Variação Uniformidade MoM' =
			
			VAR _Valor = [% Variação Uniformidade Media - MoM]
			RETURN
			
			SWITCH(
			    TRUE(),
			    _Valor > 0, "#00AA85",
			    _Valor < 0, "#ED3559",
			    _Valor = 0, "#777A8D"
			)
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: ce21b2bb-a65e-4458-9c61-2ed06794af21

	measure 'Icone % Variação Talhoes Criticos MoM' = ```
			
			VAR _Valor = [% Variação Talhoes Criticos - MoM]
			VAR _PosicaoIcones = 
			SWITCH(
			    TRUE(),
			    _Valor < 0, "Positivo",
			    _Valor > 0, "Negativo",
			    _Valor = 0, "Neutro"
			)
			VAR _Icone = 
			    CALCULATE(SELECTEDVALUE(d_Icones_Visuais[Icone URL]),d_Icones_Visuais[Icone] = _PosicaoIcones)
			
			RETURN
			_Icone
			```
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 7dedd7ad-aa07-487a-a1a6-39cea46c26d8

	measure 'Cor % Variação Talhoes Criticos - MoM' =
			
			VAR _Valor = [% Variação Talhoes Criticos - MoM]
			RETURN
			
			SWITCH(
			    TRUE(),
			    _Valor < 0, "#00AA85",
			    _Valor > 0, "#ED3559",
			    _Valor = 0, "#777A8D"
			)
		displayFolder: 00.Geral\04. Formatações Condicionais
		lineageTag: 29ba2c22-9dd0-473e-8595-751b86396b0b

	measure 'Hectares Monitorados' =
			
			SUM(fato_saude_talhao[area_saudavel_ha]) + SUM(fato_saude_talhao[area_critica_ha]) + SUM(fato_saude_talhao[area_atencao_ha])
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 397b57a7-0e4b-44c5-ae4f-c6f9ca224f9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hectares Saudaveis' =
			
			SUM(fato_saude_talhao[area_saudavel_ha])
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 16e3fbcf-6be7-42bd-b1d3-e5f80c277cb7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hectares Criticos' =
			
			SUM(fato_saude_talhao[area_critica_ha])
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: f7525333-01a6-4d01-8ce5-cca94658c793

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hectares Atenção' =
			
			SUM(fato_saude_talhao[area_atencao_ha])
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 0959481f-efac-4264-8e99-a3ab1076d6ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ultima atualização da Fazenda' =
			
			CALCULATE(
			    MAX(fato_notificacoes[data_hora]),
			    ALL(dim_calendario),
			    ALL(dim_talhao)
			)
		formatString: General Date
		displayFolder: 00.Geral\01.Monitoramento
		lineageTag: 1fafbe51-06e6-44d0-a6d8-bf5bf1b8a2aa

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

